# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e42d97ad5ed9150e231dca5a60f4182eb75ef876d229d745275fcbf9756c1a1351ac41fafc8cb00c06b48d0869f72dbd50eaef4e9a6028d824d61305c7427a83

test:
  secret_key_base: d5c8b0cbc8ef5b76b05ee773b96a853d7c90359dd99cf94ba4cbf8c84702f3da5fabd60af18d7f114168ac22467444624a5d893713a4a8e6fe74c02e0b0e0aa6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
